branches:
  only:
    - staging
    - testing
    - '1.5'
    - '1.6'
    - '1.7'
    - master
    # version tags, e.g. 1.7.1
    - /^1\.[567]\.\d+$/
    # pre-releases, e.g. 1.8-pre1
    - /^1\.8-pre\d+$/
    # test branches, e.g. test-debian
    - /^test-[\w\-\.]+$/

#dist: focal

os: linux
arch:
  - amd64
  - arm/v7
  - arm64

sudo: required
services: docker
addons:
  apt:
    packages:
# replace docker-ce by docker-compose
#      - docker-ce
      - docker-compose
env:
  - MAILU_VERSION=${TRAVIS_BRANCH////-}

language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r tests/requirements.txt
# docker compose installed as a package
#  - sudo curl -L https://github.com/docker/compose/releases/download/1.23.0-rc3/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
#  - sudo chmod +x /usr/local/bin/docker-compose

before_script:
  # - docker-compose -f tests/build.yml build
  - docker build --tag ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master} core/nginx
  - docker build --tag ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master} core/dovecot
  - docker build --tag ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master} core/postfix
  - docker build --tag ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master} core/rspamd
  - docker build --tag ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master} core/admin
  - docker build --tag ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master} core/none
  - sudo -- sh -c 'mkdir -p /mailu && cp -r tests/certs /mailu && chmod 600 /mailu/certs/*'


script:
# test.py, test name and timeout between start and tests.
  - python tests/compose/test.py core 1
#  - python tests/compose/test.py fetchmail 1
#  - travis_wait python tests/compose/test.py filters 10
#  - python tests/compose/test.py rainloop 1
#  - python tests/compose/test.py roundcube 1
#  - python tests/compose/test.py webdav 1

deploy:
  provider: script
  script: bash tests/deploy.sh
  on:
    all_branches: true
    condition: -n $DOCKER_UN
